# Generated by Django 5.0.1 on 2024-01-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author1',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title1',
        ),
    ]
