# Generated by Django 5.0.1 on 2024-01-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_department_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=70)),
                ('address1', models.CharField(max_length=90)),
                ('department1', models.ManyToManyField(to='shop.department1')),
            ],
        ),
    ]
