# Generated by Django 5.0.1 on 2024-02-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_department1_employee1'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('pages', models.IntegerField(max_length=4)),
            ],
        ),
    ]
