# Generated by Django 5.0.1 on 2024-02-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_booknew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknew',
            name='pages',
            field=models.IntegerField(),
        ),
    ]
