# Generated by Django 5.0.1 on 2024-02-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_categories_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_categories',
            new_name='ProductCategories',
        ),
    ]
