# Generated by Django 5.0.1 on 2024-02-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_product_categories_productcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
