# Generated by Django 5.0.1 on 2024-03-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productcategories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
